"""Builds tour-content-drafts.en.json from an editor's cleaned reading of the
legacy WordPress snapshot (legacy-wordpress-export.json, sha256 in that file).

Rules applied by hand: prices and durations are NOT copied (the approved
catalog is the source of truth); contradictions and unverifiable claims are
not resolved silently — they become reviewFlags for the owner; nothing here is
published until the owner approves it.
"""
import json

HOTEL = "Pickup from your hotel in Sharm El Sheikh; the exact time is confirmed on WhatsApp after booking."
QUAD_BRING = ["Headscarf", "Sunglasses", "Comfortable closed shoes"]
NOT_SUITABLE_ACTIVE = "Not suitable for pregnant women or people with back or heart problems."
WATER_BRING = ["Swimwear", "Towel", "Sunscreen", "Sunglasses"]

def t(slug, name, short, desc, includes, excludes, know, meeting=HOTEL, flags=(), facts=None):
    return {
        "slug": slug,
        "content": {
            "name": name,
            "shortDescription": short,
            "description": desc,
            "includes": includes,
            "excludes": excludes,
            "knowBeforeYouGo": know,
            "meetingPoint": meeting,
            "stops": [],
        },
        "facts": facts or {},
        "reviewFlags": list(flags),
    }

tours = [
t("super-safari-adventure", "Super Safari Adventure",
  "Quad bike through the Sinai dunes to the Valley of Echo, Bedouin tea in a tent and a camel ride.",
  "After a short drive of about 20 minutes to the quad center, our guides give you a safety briefing before you ride across the dunes towards the Echo Mountains. At the Valley of Echo you can call out and hear your voice return from the rock walls. At a Bedouin tent you relax with traditional tea, then take a camel ride across the desert before riding back to the start. On the sunset departure the evening continues with a VIP Bedouin dinner and a Tanoura and fire show before the transfer back to your hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Quad bike ride", "Camel ride", "Stops at the Valley of Echo and a Bedouin tent", "Bedouin tea", "Sunset departure: VIP Bedouin dinner with Tanoura and fire show", "Tour guide", "Entrance fees"],
  [],
  QUAD_BRING + [NOT_SUITABLE_ACTIVE, "Children under 10 ride only as passengers with an accompanying adult."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("sunset-quad-bike", "Sunset Quad Bike",
  "Ride a quad bike across the dunes as the desert turns gold, with the Valley of Echo, Bedouin tea and a camel ride at sunset.",
  "A short drive takes you to the quad center, where guides brief you on safe riding. You ride through the dunes towards the Echo Mountains as the light turns golden, stop at the Valley of Echo, relax with Bedouin tea in a tent and take a camel ride at sunset before heading back to your hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Quad bike ride", "Camel ride", "Helmet and safety briefing", "Stops at the Valley of Echo and a Bedouin tent", "Bedouin tea", "Tour guide", "Entrance fees"],
  [],
  QUAD_BRING + [NOT_SUITABLE_ACTIVE, "Children under 10 ride only as passengers with an accompanying adult."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("double-buggy-camel-ride", "Double Buggy & Camel Ride",
  "Drive a two-seat sand buggy through the dunes, stop at the Valley of Echo and a Bedouin tent, then ride a camel.",
  "After a short drive to the buggy center and a safety briefing, you and your partner drive a sand buggy across the dunes towards the Echo Mountains. You stop at the Valley of Echo and a Bedouin tent for tea, take a camel ride across the sand, and drive back to the start before your transfer to the hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Two-seat sand buggy", "Camel ride", "Stops at the Valley of Echo and a Bedouin tent", "Bedouin tea", "Safety equipment", "Tour guide", "Entrance fees"],
  [],
  QUAD_BRING + [NOT_SUITABLE_ACTIVE, "Children under 10 ride only as passengers with an accompanying adult.", "The price is per buggy, which seats two."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("bedouin-dinner-camel-ride", "Bedouin Dinner & Camel Ride",
  "Ride a camel through the dunes at sunset, then enjoy a Bedouin barbecue dinner with fire and Tanoura shows.",
  "A short drive of about 20 minutes brings you to a Bedouin village. You ride a camel through the dunes as the sun sets, then sit down to a barbecue dinner prepared by the Bedouins with fresh-baked bread and Bedouin tea. The evening ends with a fire show and a Tanoura performance before the transfer back to your hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Camel ride", "Barbecue Bedouin dinner (open buffet) in a private VIP tent", "Bedouin tea", "Fire show and Tanoura show", "Tour guide", "Entrance fees"],
  [],
  ["Comfortable clothes and shoes", "A light jacket for the evening"],
  flags=["محمد 2026-10-01: «العشاء البدوي في الخاص في اي بي انكلوديت» — الخيمة الخاصة VIP مشمولة."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("dahab-colored-canyon", "Dahab 5×1 / Colored Canyon",
  "A full day from Sharm: the Colored Canyon by jeep, lunch by the sea, a coastal camel ride, snorkeling and Dahab's bazaar.",
  "After a drive of about an hour to the Dahab area, a jeep takes you to the Colored Canyon (Salama Red Canyon), where you walk about 800 meters between sandstone walls in shades from yellow and purple to red and gold. You have lunch by the sea, ride a camel along the coast, and relax, swim and snorkel at the Three Pools. The day ends with free time in the Dahab bazaar before the drive back to Sharm.",
  ["Hotel pickup and drop-off", "Jeep to the Colored Canyon", "Guided canyon walk", "Lunch by the sea", "Camel ride along the coast", "Stop at the Three Pools", "Free time in Dahab", "Local guide"],
  [],
  ["Passport", "Snorkeling gear", "Drinking water", "Comfortable shoes", "Towel and swimwear"],
  flags=[],
  facts={"hotelPickup": "INCLUDED"}),
t("camel-horse-ride", "Camel & Horse Ride",
  "Ride a camel across the golden Sinai sands, or take the horse trail into the mountains — simple, authentic and family-friendly.",
  "Move slowly across golden sand on a traditional camel ride and take in panoramic views of the mountains and open desert. Prefer a horse? Horse rides follow the mountain trail. Either way it is a simple, authentic way to experience the Sinai landscape and Bedouin culture, and a perfect first desert experience for families and couples.",
  ["Hotel pickup and drop-off", "Camel ride in the desert or horse ride on the mountain trail", "Photo stop", "Local guide"],
  [],
  ["Comfortable clothes", "Sun protection", "Help is available to get on and off the camel."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("ras-mohamed-white-island-boat", "Ras Mohamed & White Island Boat Trip",
  "A full-day boat trip along the Sinai coast with two snorkeling stops in Ras Mohammed National Park and time on White Island.",
  "The day starts with hotel pickup at around 8:00 and a transfer to the marina. You cruise along the Sinai coastline to Ras Mohammed National Park and snorkel at two different spots in its clear water, with an optional introductory dive. Lunch is served as a buffet on deck, then you relax on the soft sand of White Island before returning to the marina and your hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Ras Mohammed National Park entrance fees", "Boat trip with two snorkeling stops", "Snorkeling guide", "Visit to White Island", "Buffet lunch on board", "Unlimited soft and hot drinks"],
  ["Snorkeling equipment (available to rent for an extra fee)", "Introductory dive (optional, extra charge)"],
  ["Sunglasses, sunscreen and a towel", "Passport or ID (a copy is accepted)", "Scuba diving is not suitable for children under 10 or pregnant women.", "Plans may change with sea and weather conditions."],
  flags=["محمد 2026-10-01: إيجار معدات السنوركل بفلوس إضافية."],
  facts={"hotelPickup": "INCLUDED", "minimumAge": None}),
t("evening-cruise", "Evening Cruise",
  "An evening on the water with dinner on board, music and a Tanoura and oriental show.",
  "From 18:00 to 22:00 you sail off Sharm El Sheikh as the city lights come on. Dinner is served on board — seafood, meat, chicken, vegetables and fruit — followed by live entertainment with jugglers, a Tanoura dance and an oriental dance show. A romantic evening for couples and a lively one for friends. Celebrating a birthday? Tell us when you book and we will make the evening a little sweeter.",
  ["Hotel pickup and drop-off", "Evening boat cruise", "Dinner on board", "Soft drinks", "Music and show"],
  [],
  ["Warm clothes in winter", "Passport", "Smart casual clothing is recommended.", "Subject to weather conditions."],
  flags=[],
  facts={"hotelPickup": "INCLUDED"}),
t("glass-bottom-boat", "Glass Bottom Boat",
  "See the Red Sea's coral reefs and fish through a glass floor — no swimming needed and ideal for all ages.",
  "Watch coral formations and marine life through the boat's glass-bottomed viewing area without getting wet. The boat sails close to well-known reef spots; the lower level is for viewing and the upper deck for sun and sea breeze. The cruise itself lasts about an hour, and you are returned to where you started.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Glass-bottom boat trip", "Entrance fees"],
  [],
  ["Sunglasses and water", "Passport or ID (a copy is accepted)", "Not wheelchair accessible; strollers are fine and infants sit on laps.", "Subject to sea conditions."],
  flags=["قراري: ماكتبتش المشروبات والمرشد في المشمول (مش مؤكدين) — لو مشمولين قولي نضيفهم."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("diving-course", "Diving Course",
  "Take your diving further with an advanced course in the Red Sea, guided by professional instructors.",
  "Explore deeper dive sites, refine your technique and enjoy the Red Sea's world-famous reefs and marine life on a multi-day course with professional instructors at one of Sharm El Sheikh's leading dive centers. Designed for certified divers who want more challenge.",
  ["Professional instructor at a leading Sharm El Sheikh dive center", "Diving equipment", "Multiple dives"],
  [],
  ["An Open Water certification is required.", "A medical declaration may be required.", "Not suitable for beginners."],
  flags=[],
  meeting="Pickup from your hotel or meeting at the dive center — confirmed on WhatsApp after booking."),
t("intro-diving", "Intro Diving",
  "Try scuba diving for the first time — a supervised introductory dive among the Red Sea's corals and fish.",
  "No licence or experience is needed. After a briefing, a professional instructor from one of Sharm El Sheikh's leading dive centers takes you on a short introductory dive to see colourful coral reefs and tropical fish in a safe, relaxed setting. Booked on request — message us on WhatsApp and we will arrange your time.",
  ["Introductory dive with a professional instructor", "Full diving equipment", "Boat trip"],
  [],
  ["No previous experience required.", "Not suitable for people with heart, ear or breathing problems.", "A medical declaration may be required.", "Not suitable for children under 10 or pregnant women."],
  flags=["بقت «بالطلب» زي ما طلبت — ملاحظة: الرحلات «بالطلب» حاليًا مخفية من الموقع. في UX-3 هخليها تظهر بزرار «اطلب على واتساب» بدل «احجز»."],
  meeting="Pickup from your hotel or meeting at the dive center — confirmed on WhatsApp after booking."),
t("private-boat", "Private Boat",
  "Your own boat for the day to Tiran Island or Ras Mohammed, with snorkeling stops and lunch on board — on request.",
  "Choose Tiran Island or Ras Mohammed National Park and a half or full day. A private transfer picks you up at around 9:00, and you snorkel or dive at two spots, have a buffet lunch on deck and spend quality time with your group. Suitable for groups of up to 15 people. Price on request.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Private boat with captain and crew", "Snorkeling equipment", "Entrance fees", "Buffet lunch", "Unlimited soft and hot drinks"],
  [],
  ["Sunglasses, sunscreen and a towel", "Passport or ID (a copy is accepted)", "Scuba diving is not suitable for children under 10 or pregnant women.", "Book in advance; route and duration can be customised."],
  flags=["رحلة «بالطلب» (سعر على الطلب) — هتفضل مش قابلة للحجز المباشر زي ما هي."],
  facts={"hotelPickup": "INCLUDED"}),
t("sinai-dream-sailboat", "Sinai Dream Sailboat",
  "A day on a comfortable sailboat with three snorkeling stops and a seafood buffet lunch.",
  "Sail along the coast with three stops for snorkeling over colourful coral. The sailboat has an upper deck with seating, sun loungers, indoor lounges and swings over the sea. A seafood buffet lunch and drinks are served on board.",
  ["Hotel pickup and drop-off", "Sailboat trip", "Three snorkeling stops", "Snorkeling equipment", "Seafood buffet lunch", "Soft drinks", "Professional crew"],
  [],
  WATER_BRING + ["Limited number of guests on board.", "Subject to weather and sea conditions."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("ras-mohamed-by-bus", "Ras Mohamed by Bus",
  "A half day in Ras Mohammed National Park by road: snorkeling, mangroves, the Magic Lake and the Earth Crack.",
  "About 30 minutes from Sharm, Ras Mohammed National Park welcomes you at the Allah Gate. You snorkel over coral in the park's clear water, walk among the mangroves, swim in the salty Magic Lake, see the Earth Crack and climb a cliff for a panoramic photo before returning to your hotel. The trip runs from about 8:00 to 14:00.",
  ["Hotel pickup and drop-off", "Air-conditioned bus", "Snorkeling guide", "Ras Mohammed National Park entrance fees"],
  ["Food and drinks"],
  ["Snorkeling gear, swimwear and a towel", "Snacks and water", "Sunglasses, sunscreen and comfortable shoes"],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("banana-boat", "Banana Boat",
  "Hold on tight as a speedboat pulls your banana boat across the waves — a quick, fun water ride.",
  "You are picked up from your hotel and taken to the beach, where the crew gives a safety briefing and life jackets. Then it's a fast ride across the waves on the banana boat as you try to stay on.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Banana boat ride", "Life jacket and safety briefing"],
  [],
  ["Sun hat, sunglasses and a towel", "Basic swimming skills are recommended.", NOT_SUITABLE_ACTIVE, "Not suitable for children under 10."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "minimumAge": 10}),
t("parasailing-adventure", "Parasailing Adventure",
  "Fly high above the Red Sea for a bird's-eye view of the coast — solo or with a partner.",
  "After hotel pickup and a safety briefing, a boat takes you out and you rise above the sea on a parachute for around 7 minutes, taking in the coastline from above, alone or with your partner. No experience is needed.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Parasailing flight", "Boat ride", "Safety equipment", "Professional crew"],
  [],
  ["Sun hat, sunglasses and a towel", NOT_SUITABLE_ACTIVE, "Not suitable for children under 10.", "Weather dependent."],
  facts={"hotelPickup": "INCLUDED", "minimumAge": 10}),
t("speed-boat-adventure", "Speed Boat Adventure",
  "A private speedboat for your group to Tiran Island: snorkel the reefs, pass the shipwreck and look out for dolphins.",
  "Three hours on your own private RIB speedboat for up to 5 people, with an experienced captain. Snorkel at Tiran Island's reefs, pass the historic shipwreck and keep an eye out for dolphins in the wild. Life jackets, snorkel masks and a cooler with drinks are on board. Book at least 2 days in advance.",
  ["Hotel pickup and drop-off by air-conditioned minibus", "Private speedboat with captain", "Snorkel mask", "Cooler with drinks", "Life jackets"],
  ["Tips for the captain", "Personal expenses"],
  ["Book at least 2 days in advance.", "Up to 5 people per boat; the price is per boat.", "Not suitable for pregnant women or people with back or neck problems.", "Subject to sea and weather conditions."],
  flags=["قراري: المدة «3 ساعات مركب خاص» (تناسب سعر 150€ للمركب) — لو غلط قولي."],
  facts={"hotelPickup": "INCLUDED"}),
t("submarine", "Submarine",
  "Watch fish and coral through large windows from an underwater viewing cabin — no swimming needed.",
  "A short drive takes you to the jetty and a 15-minute sail along the coast. You then descend to the underwater cabin for about 45 minutes of reef and fish viewing through large panoramic windows — you may even wave to divers outside — before sailing back.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Submarine trip", "Tour guide", "Entrance fees"],
  [],
  ["Passport or ID (a copy is accepted)", "A bottle of water", "Not suitable for wheelchair users.", "Subject to sea and weather conditions."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("tiran-island-boat-trip", "Tiran Island Boat Trip",
  "A full-day boat trip to Tiran Island with two snorkeling stops, buffet lunch on board and a chance to spot dolphins.",
  "Pickup at around 8:00 takes you to the marina for a cruise along the Sharm coast towards Tiran Island — with luck you may see dolphins on the way. You snorkel at two different spots, with an optional introductory dive, and enjoy a buffet lunch on deck before returning to the marina and your hotel.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Entrance fees", "Boat trip with two snorkeling stops", "Buffet lunch on board", "Unlimited soft and hot drinks"],
  ["Snorkeling equipment (available to rent for an extra fee)", "Introductory dive (optional, extra charge)"],
  ["Sunglasses, sunscreen and a towel", "Passport or ID (a copy is accepted)", "Scuba diving is not suitable for children under 10 or pregnant women."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("tube-boat", "Tube Boat",
  "Glide over the water on an inflatable tube pulled by a speedboat — a short, splashy thrill.",
  "After hotel pickup and a safety briefing on the beach, you ride an inflatable tube pulled by a speedboat across the water.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Tube ride", "Life jacket and safety briefing"],
  [],
  ["Sun hat, sunglasses and a towel", "Basic swimming skills are recommended.", NOT_SUITABLE_ACTIVE, "Not suitable for children under 10."],
  facts={"hotelPickup": "INCLUDED", "minimumAge": 10}),
t("cairo-by-bus", "Cairo by Bus",
  "A long day trip by road to Cairo: the Egyptian Museum with an Egyptologist, lunch by the Nile and the Pyramids of Giza.",
  "Travel by bus to Cairo and start at the Egyptian Museum, where an Egyptologist guides you through highlights including the treasures of Tutankhamun. After lunch at a restaurant on the Nile, you visit papyrus and perfume workshops and then the Giza Plateau with the Pyramids of Khufu, Khafre and Menkaure and the Great Sphinx, before the long ride back to Sharm.",
  ["Hotel pickup and drop-off", "Air-conditioned bus", "Egyptologist guide", "Entrance fees to the sites in the program", "Lunch and drinks"],
  [],
  ["Passport", "Comfortable clothing, a hat and sunscreen", "It is a very long day with many hours on the road."],
  flags=["قراري: المدة 20–24 ساعة زي الكتالوج (الطريق من شرم طويل). وصلّحت عمر الأهرامات الغلط."],
  facts={"hotelPickup": "INCLUDED"}),
t("cairo-by-plane", "Cairo by Plane",
  "Fly to Cairo for the day: the Egyptian Museum, lunch by the Nile, the Pyramids and the Sphinx, then fly back.",
  "An early pickup (around 4–5 am) takes you to Sharm airport for your flight to Cairo, where your English-speaking guide meets you. Visit the Egyptian Museum, have lunch with a view of the Nile, stop at a perfume workshop, explore the Giza Plateau with the Pyramids and the Sphinx, and visit a papyrus institute before your flight back. Runs on Sundays and Thursdays.",
  ["Hotel–airport transfers in Sharm and all transfers in Cairo", "Return flights Sharm–Cairo", "English-speaking guide", "Entrance fees to the sites in the program", "Lunch in Cairo"],
  ["Drinks at the restaurant", "Optional felucca ride on the Nile", "Entry inside the two larger pyramids"],
  ["Passport (required for the flight)", "You may take a breakfast box from your hotel.", "Pickup around 5:00, return around 22:00."],
  flags=["قراري: الأحد والخميس بس — المواعيد في النظام هتتفتح الأيام دي بس."],
  facts={"hotelPickup": "INCLUDED", "guideLanguages": ["en"]}),
t("mount-sinai-st-catherine", "Mount Sinai & St. Catherine",
  "Climb Mount Sinai overnight to watch the sunrise from the summit, then visit St. Catherine's Monastery.",
  "Pickup is around 20:00 for a drive of about 4 hours. You climb Mount Sinai (2,285 m), finishing with some 750 steps, in 2–3 hours to watch the sunrise from the top. After descending you visit St. Catherine's Monastery and the Chapel of the Burning Bush before returning to Sharm around 13:30. Camels can carry you only for the first part of the path.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Guided climb", "Visit to St. Catherine's Monastery"],
  [],
  ["Passport or ID", "Hiking shoes and a warm jacket (it is cold at the top, especially in winter)", "Water, snacks and a power bank", "Not suitable for pregnant women, children, older guests or people with back, heart or breathing problems.", "Runs on Sundays, Wednesdays and Fridays."],
  flags=["قراري: الأحد والأربع والجمعة — المواعيد في النظام هتتفتح الأيام دي بس."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": False}),
t("luxor-by-plane", "Luxor by Plane",
  "Fly to Luxor for the day: the Valley of the Kings, Hatshepsut's temple, the Colossi of Memnon and Karnak.",
  "An early transfer takes you to Sharm airport for the short flight to Luxor. With an Egyptologist you visit the Valley of the Kings, the Temple of Hatshepsut at Deir el-Bahari and the Colossi of Memnon, have lunch at a local restaurant, and explore Karnak Temple and its Hypostyle Hall before flying back in the evening.",
  ["Hotel–airport transfers", "Return flights Sharm–Luxor", "Egyptologist guide", "Entrance fees to the sites in the program", "Lunch at a local restaurant"],
  ["Special tombs such as Tutankhamun's", "Personal expenses and tips"],
  ["Passport (required for the flight)", "Comfortable walking shoes", "Hat, sunglasses and sunscreen"],
  flags=["قراري: السعر المعروض €280 زي الكتالوج."],
  facts={"hotelPickup": "INCLUDED"}),
t("st-catherine-dahab", "St. Catherine & Dahab",
  "Visit St. Catherine's Monastery, then lunch and free time in Dahab — a relaxed cultural day.",
  "Visit the famous St. Catherine's Monastery with its historic church, icon gallery, the Burning Bush and library. Afterwards you have lunch at a restaurant in Dahab and free time to stroll the town before returning to Sharm. A comfortable day for history lovers and travellers seeking a spiritual experience.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Visit to St. Catherine's Monastery", "Lunch in Dahab", "Free time in Dahab", "Local guide"],
  [],
  ["Passport", "Comfortable walking shoes", "Runs on Mondays, Thursdays and Saturdays."],
  flags=["قراري: الأيام الاتنين والخميس والسبت. شِلت «مطعم 4 نجوم» لحد ما تتأكد."],
  facts={"hotelPickup": "INCLUDED"}),
t("turkish-bath", "Turkish Bath",
  "A traditional hammam ritual: sauna, jacuzzi and steam, peeling, soap massage and a relaxing massage.",
  "Step into a traditional Turkish bath and enjoy the sauna, jacuzzi and steam room, followed by peeling, a foam soap massage, a face mask, sea-salt treatment for hands and feet and a relaxing body massage.",
  ["Hotel pickup and drop-off", "Sauna, jacuzzi and steam room", "Peeling and soap massage", "Face mask", "Body massage", "Towels"],
  [],
  ["For adults.", "Book ahead in high season."],
  flags=["قراري: ماكتبتش مدة المساج (30 ولا 50 متعارضين) — لو عايز نكتبها قولي."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": False}),
t("dolphin-show", "Dolphin Show",
  "An hour-long dolphin show in Sharm with jumps, spins and a look at how dolphins communicate.",
  "A pickup of about 20 minutes takes you to the venue for a one-hour show in which dolphins jump, spin and swim, with explanations about how they communicate and behave.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Show entrance ticket"],
  [],
  ["Photography only in designated areas.", "Show times may vary by season."],
  flags=["قراري: العرض مستمر. شِلت ادعاء «جهود الحماية» لأنه محتاج دليل."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("swimming-with-dolphins", "Swimming with Dolphins",
  "Fifteen minutes in the water with dolphins, supervised by trainers, with a life jacket provided.",
  "After a 20-minute drive to the venue you spend 15 minutes in the water with dolphins under the supervision of trainers, with a life jacket provided. Phones are not allowed in the water; professional photos and videos can be bought.",
  ["Hotel pickup and drop-off", "Air-conditioned transport", "Entrance ticket", "15 minutes swimming with dolphins", "Life jacket"],
  ["Professional photos and videos (available to buy)"],
  ["Swimwear, towel, sunglasses and sunscreen", "Phones are not allowed while swimming.", "Non-swimmers may need assistance."],
  flags=[],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("crocodile-show", "Crocodile Show",
  "A one-hour crocodile show where trainers demonstrate how these animals are handled.",
  "Watch skilled trainers work with crocodiles in a one-hour show in Sharm El Sheikh.",
  ["Hotel pickup and drop-off", "Show entrance ticket"],
  [],
  ["Children must be accompanied by adults.", "Photography only in designated areas.", "Show times may vary."],
  flags=["اتلغت زي ما طلبت — مخفية من الموقع."],
  facts={"hotelPickup": "INCLUDED", "childrenAllowed": True}),
t("sharm-airport-transfer", "Sharm Airport Transfer",
  "Private transfer between your hotel and Sharm El Sheikh airport by car or minibus.",
  "Our driver collects you from your hotel reception and takes you directly to Sharm El Sheikh International Airport, or meets you on arrival. Choose the vehicle that fits your group: a sedan (€15), a higher SUV (€20) or a Hiace minibus (€35) — the price is per vehicle, not per person.",
  ["Private vehicle for your group", "Professional driver", "Luggage assistance"],
  [],
  ["Please send your flight details when booking.", "Sedan: up to 4 people and 3 suitcases. Hiace minibus: up to 8 guests."],
  meeting="Your hotel reception, or the arrivals hall at Sharm El Sheikh airport.",
  flags=["ملاحظة تقنية: الحجز حاليًا بسعر واحد للفرد. اختيار نوع العربية (15/20/35) محتاج إضافة في نظام الحجز — هعملها في UX-4."]),
]

assert len(tours) == 30 and len({x["slug"] for x in tours}) == 30
out = {
    "schemaVersion": 1,
    "status": "OWNER_APPROVED",
    "approval": "Owner reviewed owner-edited-2026-09-30.xlsx and delegated the remaining decisions to Claude in writing on 2026-09-30 ('كمل شغلك ومعاك إذن صريح … التفكير والاقتراح والإضافة'). Claude's decisions are recorded as 'قراري' notes per tour.",
    "locale": "en",
    "source": "legacy-wordpress-export.json (editor-cleaned; prices/durations come from approved-catalog.json)",
    "tours": tours,
}
json.dump(out, open("tour-content-drafts.en.json", "w"), ensure_ascii=False, indent=2)
print("written", len(tours), "tours;", sum(len(x["reviewFlags"]) for x in tours), "review flags")
