import type { ErpLocale } from "./erpLocale";
export const categoryEn = {
  title: "Category covers", subtitle: "Manage real cover photos for the five existing tour categories. This does not create categories or change tours, prices or availability.", noCover: "No cover photo uploaded", missing: "The category media record is unavailable. Upload and approval are disabled; check the backend migration.", save: "Save alternative text", saved: "Category alternative text saved and verified. Changed text needs rights approval again.", uploaded: "Category cover uploaded as an unpublished draft and verified.", approved: "Category photo rights approved for the reviewed revision.", conflict: "This category changed while you were editing. Your text is kept, but writes are blocked to protect newer data. Copy your changes, then reload the saved text and review again.", discard: "Discard local text & reload saved copy", refresh: "Refresh categories", draftHelp: "Alternative text can be prepared before upload. Unknown descriptions stay empty; only approved cover rights permit public delivery.", select: "Choose a category", leave: "You have unsaved category text or selected photo files. Leave this page and discard local changes?", review: "Review category photo rights", revision: "Saved revision", ready: "Five existing categories; one cover each", unknownState: "Saved category state could not be verified. Local edits are kept. Refresh before making another change.",
} as const;
export type CategoryMessageKey = keyof typeof categoryEn;
export const categoryAr: Record<CategoryMessageKey, string> = {
  title: "أغلفة الفئات", subtitle: "إدارة صور أغلفة حقيقية للفئات الخمس الموجودة. لا تنشئ هذه الشاشة فئات جديدة ولا تغيّر الرحلات أو الأسعار أو الإتاحة.", noCover: "لم تُرفع صورة غلاف", missing: "سجل صورة الفئة غير متاح. الرفع والاعتماد معطّلان؛ راجع تهيئة قاعدة البيانات.", save: "حفظ النص البديل", saved: "تم حفظ النص البديل للفئة والتحقق منه. تعديل النص يحتاج إلى اعتماد الحقوق مجددًا.", uploaded: "تم رفع غلاف الفئة كمسودة غير منشورة والتحقق منه.", approved: "تم اعتماد حقوق صورة الفئة بالنسخة التي تمت مراجعتها.", conflict: "تغيرت هذه الفئة أثناء تعديلك. نصك محفوظ، لكن الكتابة معطلة لحماية البيانات الأحدث. انسخ تعديلاتك ثم أعد تحميل النص المحفوظ وراجعه مجددًا.", discard: "تجاهل النص المحلي وإعادة تحميل النسخة المحفوظة", refresh: "تحديث الفئات", draftHelp: "يمكن تجهيز النص البديل قبل الرفع. اترك الأوصاف غير المؤكدة فارغة؛ اعتماد حقوق الغلاف شرط لعرضه العام.", select: "اختيار الفئة", leave: "لديك نصوص فئات غير محفوظة أو ملفات صور مختارة. هل تريد مغادرة الصفحة وفقد التعديلات المحلية؟", review: "مراجعة حقوق صورة الفئة", revision: "النسخة المحفوظة", ready: "خمس فئات موجودة؛ غلاف واحد لكل فئة", unknownState: "تعذر التحقق من الحالة المحفوظة للفئات. تعديلاتك المحلية محفوظة. حدّث الحالة قبل أي تعديل آخر.",
};
export const categoryMessage = (locale: ErpLocale, key: CategoryMessageKey) => (locale === "ar" ? categoryAr : categoryEn)[key];
