import { ToursApiError } from "../composables/useToursApi";
import type { ErpLocale } from "./erpLocale";

export const contentEn = {
  uploadAndApprove: "Upload & approve photo", uploadAndApproveRights: "I own or have permission to use this photo and its description. Approve it after upload.", uploadedApproved: "Photo uploaded, rights approved and verified. Published tour pages can now show it.", uploadedNeedsApproval: "The upload returned a photo, but approval could not be verified. Check that photo's saved status and use Review photo rights if needed; do not upload it again.",
  title: "Content & photos", subtitle: "Edit verified tour information. Saving a draft never changes the public site.",
  photoConflict: "The saved photo list changed while you were editing. Your local edits are kept, but saving is blocked to protect newer uploads. Copy your edits, then discard the local photo changes and review the latest list.", discardPhotoEdits: "Discard local photo edits & reload list",
  language: "Content language", draft: "Saved draft", published: "Published", missing: "Not created", unsaved: "Unsaved changes", clean: "No unsaved changes",
  name: "Tour title", shortDescription: "Short description", description: "Full description", includes: "Included", excludes: "Not included", knowBeforeYouGo: "Know before you go", meetingPoint: "Meeting point",
  listHelp: "One item per line. Up to 20 items, 200 characters each. Leave unknown details empty.", requiredHelp: "Title, short description and full description are required to save text. Enter only approved factual information.",
  save: "Save draft", saving: "Working…", publish: "Review & publish", unpublish: "Remove from public site", saved: "Draft saved and refreshed from the server.", publishedNotice: "Reviewed draft published.", unpublished: "Published content removed. The draft is kept.",
  preview: "Saved public copy", noPublished: "No text is published in this language. The public site may use its documented language fallback.", review: "Review saved draft", reviewHelp: "This exact saved revision will be published. Verify the facts and spelling before confirming.", confirmPublish: "Publish this revision", confirmUnpublish: "Remove this published copy?", confirmUnpublishHelp: "This removes only the published copy; saved drafts are preserved.",
  refresh: "Refresh saved state", refreshHelp: "Refresh preserves your local unsaved edits. Check the latest saved draft before publishing.", revision: "Reviewed revision", updated: "Updated", saveFirst: "Save and review changes before publishing.", cannotPublish: "Your account can edit but cannot publish. A staff publisher must review the saved draft.", readOnly: "Read-only access. Editing requires tour-manage permission.",
  facts: "Shared tour facts", factsHelp: "Facts apply to all four languages. Unknown means no claim is displayed. Prices, availability and payments are not edited here.", unknown: "Not stated", yes: "Yes", no: "No", children: "Children allowed", minimumAge: "Minimum age", languages: "Guide language codes", languageHelp: "Use verified two-letter lowercase codes separated by commas, up to 10 distinct codes.", pickup: "Hotel pickup", pickupIncluded: "Included", pickupExcluded: "Not included", pickupSome: "Some areas", factsPreview: "Published facts", noPublishedFacts: "No shared facts are published.",
  stops: "Itinerary stops", stopKey: "Stable stop key", stopName: "Stop title", stopDescription: "Stop description", stopHelp: "Text keys must match the relevant shared itinerary stop. Do not invent locations.", addStop: "Add a stop", removeStop: "Remove stop", kind: "Stop type", stop: "Visit stop", meetingStop: "Meeting point", latitude: "Latitude", longitude: "Longitude", coordinatesHelp: "Enter verified coordinates only. At most 12 stops and one meeting point.",
  photos: "Tour photos", photosHelp: "Rights approval is separate from text publishing. Upload and photo editing will appear when their verified storage contract is available.", noPhotos: "No photos are linked to this tour.", approved: "Rights approved", photoDraft: "Rights not approved", photoCount: "Linked photos", cover: "Cover", alt: "Alternative text", leave: "You have unsaved content or facts. Leave this page and discard local edits?", invalid: "Some fields exceed their limits or contain invalid values. Check the form before saving.",
  conflict: "The saved draft changed after review. Latest saved state was refreshed when possible; your local edits were kept. Review again before publishing.", nothing: "There is no saved draft or published copy for that action. Refresh the saved state.", forbidden: "You do not have permission for this action.", expired: "Your session expired. Sign in again.", notFound: "This tour or content item was not found.", failed: "The action could not be verified. Your local edits are kept. Refresh before retrying.", offline: "Could not reach the server. Your local edits are kept.",
  upload: "Upload photo", uploadHelp: "JPEG or PNG only, up to 10 MiB and 24 million pixels. The server validates and re-encodes the image, removing metadata. Uploading does not publish it.", choosePhoto: "Choose a real photo", fileInvalid: "Choose a non-empty JPEG/PNG file no larger than 10 MiB.", uploaded: "Photo uploaded as a draft and verified from the server.", uploadUncertain: "Upload result could not be verified. Check the refreshed photo list before choosing the file again; do not blindly retry.", clearFile: "Clear selection", replacePhoto: "Replace file", newPhoto: "Add a new photo", altHelp: "Describe the actual image in each language. English alt text is required for rights approval. Changing alt or file resets rights to draft.", savePhotos: "Save photo metadata", metadataSaved: "Photo metadata saved and verified.", moveUp: "Move earlier", moveDown: "Move later", removePhoto: "Unlink photo", removeHelp: "Unlinking removes the image from this tour, not your original device file.", approveRights: "Review photo rights", rightsConfirm: "Confirm rights and approve", rightsHelp: "Confirm the business has permission to publish this actual photo and its alternative text. This approves only the reviewed revision; it does not publish text or change pricing.", previewFailed: "The photo preview could not be loaded. Rights approval is disabled until the actual image can be reviewed.", rightsApproved: "Reviewed photo rights approved.", photosDirty: "Save photo changes before reviewing rights.", photoLimit: "A tour supports up to 30 linked photos.",
} as const;
export type ContentMessageKey = keyof typeof contentEn;
export const contentAr: Record<ContentMessageKey, string> = {
  uploadAndApprove: "رفع واعتماد الصورة", uploadAndApproveRights: "أملك الصورة أو لدي إذن باستخدامها ووصفها. اعتمدها بعد الرفع.", uploadedApproved: "تم رفع الصورة واعتماد حقوقها والتحقق منها. يمكن عرضها الآن في صفحات الرحلة المنشورة.", uploadedNeedsApproval: "عاد الرفع بصورة، لكن لم نتأكد من اعتمادها. راجع حالتها المحفوظة واستخدم مراجعة حقوق الصورة عند الحاجة؛ لا ترفعها مرة أخرى.",
  title: "المحتوى والصور", subtitle: "عدّل معلومات الرحلة المعتمدة. حفظ المسودة لا يغيّر الموقع العام.",
  photoConflict: "تغيرت قائمة الصور المحفوظة أثناء تعديلك. تعديلاتك المحلية محفوظة، لكن الحفظ معطل لحماية الصور الأحدث. انسخ تعديلاتك ثم تجاهل التعديلات المحلية للصور وراجع القائمة الحديثة.", discardPhotoEdits: "تجاهل تعديلات الصور المحلية وتحديث القائمة",
  language: "لغة المحتوى", draft: "المسودة المحفوظة", published: "منشور", missing: "لم يُنشأ", unsaved: "تعديلات غير محفوظة", clean: "لا توجد تعديلات غير محفوظة",
  name: "عنوان الرحلة", shortDescription: "الوصف المختصر", description: "الوصف الكامل", includes: "يشمل", excludes: "لا يشمل", knowBeforeYouGo: "معلومات قبل الذهاب", meetingPoint: "نقطة اللقاء",
  listHelp: "عنصر واحد في كل سطر. بحد أقصى 20 عنصرًا و200 حرف لكل عنصر. اترك التفاصيل غير المؤكدة فارغة.", requiredHelp: "عنوان الرحلة والوصف المختصر والكامل مطلوبة لحفظ النص. اكتب المعلومات الواقعية المعتمدة فقط.",
  save: "حفظ المسودة", saving: "جارٍ التنفيذ…", publish: "مراجعة ونشر", unpublish: "إزالة من الموقع العام", saved: "تم حفظ المسودة وتحديثها من الخادم.", publishedNotice: "تم نشر المسودة التي تمت مراجعتها.", unpublished: "تمت إزالة النسخة المنشورة. المسودة محفوظة.",
  preview: "النسخة العامة المحفوظة", noPublished: "لا يوجد نص منشور بهذه اللغة. قد يستخدم الموقع اللغة البديلة وفق قواعده المعلنة.", review: "مراجعة المسودة المحفوظة", reviewHelp: "سيتم نشر هذه النسخة المحفوظة بالضبط. تأكد من المعلومات والكتابة قبل التأكيد.", confirmPublish: "نشر هذه النسخة", confirmUnpublish: "إزالة هذه النسخة المنشورة؟", confirmUnpublishHelp: "تُحذف النسخة المنشورة فقط؛ تبقى المسودات المحفوظة.",
  refresh: "تحديث الحالة المحفوظة", refreshHelp: "التحديث يحتفظ بتعديلاتك المحلية غير المحفوظة. راجع آخر مسودة محفوظة قبل النشر.", revision: "النسخة التي تمت مراجعتها", updated: "آخر تحديث", saveFirst: "احفظ التعديلات وراجعها قبل النشر.", cannotPublish: "يمكن لحسابك التعديل دون النشر. يحتاج نشر المسودة إلى مراجعة موظف لديه صلاحية النشر.", readOnly: "عرض فقط. التعديل يحتاج إلى صلاحية إدارة الرحلات.",
  facts: "حقائق الرحلة المشتركة", factsHelp: "تطبق الحقائق على اللغات الأربع. غير محدد يعني عدم عرض ادعاء. الأسعار والإتاحة والدفع لا تُعدّل هنا.", unknown: "غير محدد", yes: "نعم", no: "لا", children: "مسموح للأطفال", minimumAge: "الحد الأدنى للعمر", languages: "أكواد لغات المرشد", languageHelp: "أكواد معتمدة من حرفين إنجليزيين صغيرين، مفصولة بفواصل، بحد أقصى 10 أكواد مختلفة.", pickup: "الانتقال من الفندق", pickupIncluded: "مشمول", pickupExcluded: "غير مشمول", pickupSome: "في بعض المناطق", factsPreview: "الحقائق المنشورة", noPublishedFacts: "لا توجد حقائق مشتركة منشورة.",
  stops: "محطات الرحلة", stopKey: "كود المحطة الثابت", stopName: "عنوان المحطة", stopDescription: "وصف المحطة", stopHelp: "يجب أن يطابق كود النص المحطة المقابلة في حقائق الرحلة المشتركة. لا تضف مواقع غير مؤكدة.", addStop: "إضافة محطة", removeStop: "إزالة المحطة", kind: "نوع المحطة", stop: "محطة زيارة", meetingStop: "نقطة لقاء", latitude: "خط العرض", longitude: "خط الطول", coordinatesHelp: "أدخل الإحداثيات المؤكدة فقط. بحد أقصى 12 محطة ونقطة لقاء واحدة.",
  photos: "صور الرحلة", photosHelp: "اعتماد حقوق الصور مستقل عن نشر النص. يظهر رفع الصور وتحريرها بعد توفر عقد التخزين المختبر.", noPhotos: "لا توجد صور مرتبطة بهذه الرحلة.", approved: "الحقوق معتمدة", photoDraft: "الحقوق غير معتمدة", photoCount: "الصور المرتبطة", cover: "الغلاف", alt: "النص البديل", leave: "لديك تعديلات في المحتوى أو الحقائق لم تُحفظ. هل تريد مغادرة الصفحة وفقد التعديلات المحلية؟", invalid: "بعض الحقول تتجاوز الحدود أو تحتوي قيمًا غير صحيحة. راجع النموذج قبل الحفظ.",
  conflict: "تغيرت المسودة المحفوظة بعد المراجعة. تم تحديث آخر حالة محفوظة إن أمكن، مع الاحتفاظ بتعديلاتك المحلية. راجعها مرة أخرى قبل النشر.", nothing: "لا توجد مسودة محفوظة أو نسخة منشورة لهذا الإجراء. حدّث الحالة المحفوظة.", forbidden: "ليس لديك صلاحية تنفيذ هذا الإجراء.", expired: "انتهت جلستك. سجل الدخول مجددًا.", notFound: "الرحلة أو عنصر المحتوى غير موجود.", failed: "لم نتمكن من التحقق من الإجراء. تعديلاتك المحلية محفوظة. حدّث الحالة قبل المحاولة مجددًا.", offline: "تعذر الاتصال بالخادم. تعديلاتك المحلية محفوظة.",
  upload: "رفع الصورة", uploadHelp: "JPEG أو PNG فقط، بحد أقصى 10 MiB و24 مليون بكسل. يتحقق الخادم من الصورة ويعيد ترميزها ويحذف بياناتها الوصفية. الرفع لا ينشر الصورة.", choosePhoto: "اختيار صورة حقيقية", fileInvalid: "اختر ملف JPEG أو PNG غير فارغ ولا يزيد على 10 MiB.", uploaded: "تم رفع الصورة كمسودة والتحقق منها من الخادم.", uploadUncertain: "لم نتمكن من التحقق من نتيجة الرفع. راجع قائمة الصور المحدثة قبل اختيار الملف مرة أخرى؛ لا تكرر الرفع دون تحقق.", clearFile: "مسح الاختيار", replacePhoto: "استبدال الملف", newPhoto: "إضافة صورة جديدة", altHelp: "صف الصورة الفعلية بكل لغة. النص البديل الإنجليزي مطلوب لاعتماد الحقوق. تغيير النص البديل أو الملف يعيد الحقوق إلى مسودة.", savePhotos: "حفظ بيانات الصور", metadataSaved: "تم حفظ بيانات الصور والتحقق منها.", moveUp: "نقل للأمام", moveDown: "نقل للخلف", removePhoto: "فك ارتباط الصورة", removeHelp: "فك الارتباط يزيل الصورة من هذه الرحلة ولا يحذف صورتك الأصلية من جهازك.", approveRights: "مراجعة حقوق الصورة", rightsConfirm: "تأكيد الحقوق والاعتماد", rightsHelp: "أكد أن الشركة تملك حق نشر الصورة الفعلية ونصها البديل. يعتمد ذلك النسخة التي تراجعها فقط؛ ولا ينشر النص أو يغيّر الأسعار.", previewFailed: "تعذر تحميل معاينة الصورة. اعتماد الحقوق معطل حتى تتمكن من مراجعة الصورة الفعلية.", rightsApproved: "تم اعتماد حقوق الصورة التي تمت مراجعتها.", photosDirty: "احفظ تعديلات الصور قبل مراجعة الحقوق.", photoLimit: "يمكن ربط 30 صورة كحد أقصى لكل رحلة.",
};

export const contentMessage = (locale: ErpLocale, key: ContentMessageKey) => (locale === "ar" ? contentAr : contentEn)[key];
export function contentErrorKey(error: unknown): ContentMessageKey {
  if (!(error instanceof ToursApiError)) return "offline";
  if (error.status === 401) return "expired";
  if (error.status === 403) return "forbidden";
  if (error.status === 404) return "notFound";
  if (error.errorCode === "draft_changed") return "conflict";
  if (error.errorCode === "nothing_to_publish") return "nothing";
  if (error.errorCode === "invalid_content") return "invalid";
  return "failed";
}
