server {
    listen 8080;
    default_type application/json;
    return 200 '{"host":"$host","xff":"$http_x_forwarded_for","proto":"$http_x_forwarded_proto","forwarded":"$http_forwarded","xfhost":"$http_x_forwarded_host","xfprefix":"$http_x_forwarded_prefix"}';
}
